server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema\=test
    username: postgres
    password: postgres

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        order_by:
          default_null_ordering: last

aws:
  bucket-name: ${BUCKET_NAME}
  region: ${REGION}
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}


